<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTjxDU6V\SimpleSAML_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTjxDU6V/SimpleSAML_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTjxDU6V.legacy');

    return;
}

if (!\class_exists(SimpleSAML_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTjxDU6V\SimpleSAML_KernelProdContainer::class, SimpleSAML_KernelProdContainer::class, false);
}

return new \ContainerTjxDU6V\SimpleSAML_KernelProdContainer([
    'container.build_hash' => 'TjxDU6V',
    'container.build_id' => '4de1efc8',
    'container.build_time' => 1683793296,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTjxDU6V');
