<?php
/* This file was generated by the metarefresh module at 2023-09-01T08:01:03Z
Do not update it manually as it will get overwritten
*/

$metadata['http://DEV-FS-ONE.GRPLEG.COM/adfs/services/trust'] = array (
  'entityid' => 'http://DEV-FS-ONE.GRPLEG.COM/adfs/services/trust',
  'contacts' => 
  array (
    0 => 
    array (
      'contactType' => 'support',
    ),
  ),
  'metadata-set' => 'saml20-idp-remote',
  'SingleSignOnService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://dev-fs-one.grpleg.com/adfs/ls/',
    ),
    1 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
      'Location' => 'https://dev-fs-one.grpleg.com/adfs/ls/',
    ),
  ),
  'SingleLogoutService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://dev-fs-one.grpleg.com/adfs/ls/',
    ),
    1 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
      'Location' => 'https://dev-fs-one.grpleg.com/adfs/ls/',
    ),
  ),
  'ArtifactResolutionService' => 
  array (
  ),
  'NameIDFormats' => 
  array (
    0 => 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
    1 => 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
    2 => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
  ),
  'keys' => 
  array (
    0 => 
    array (
      'encryption' => true,
      'signing' => false,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIIC7DCCAdSgAwIBAgIQEToU56KUurZD1YaMEtkjoDANBgkqhkiG9w0BAQsFADAyMTAwLgYDVQQDEydBREZTIEVuY3J5cHRpb24gLSBERVYtRlMtT05FLkdSUExFRy5DT00wHhcNMjMwNDI2MDAxMjA1WhcNMjgwNDI1MDAxMjA1WjAyMTAwLgYDVQQDEydBREZTIEVuY3J5cHRpb24gLSBERVYtRlMtT05FLkdSUExFRy5DT00wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCgTjv3GDfz785sZLFaiH3UgN7oa1NqgnzdX8WjfOz1FHSCJEBU2u26u+DH/SjAbeweyV5sYZdnASYGaS3WR8ReFjqVNrja9Cn6Utzr/jVVQfuTRJDuGtLP09monYHyjeVSgUZWf39bej33gCGWOfXuAAAyltgGKOXccoAnBtamB/v80iLqq1cest/u5SFMlpQ0QvNROkpKzl+yDQ+63opqX+sbgHRyQHEE0/CwTZPIx5xuM1m0cF9QWhVaReziFH8WL5Pcj5o07R2xFVG8z4ismGHmJkp8oOi6btnNTiqdiYbX6dKgfEtvNwgM81Qee9CHw13jYeVgZpcQamy81QBRAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAEiRJXVSm1zbtU4zju+Vp1z0jhA9RX+ALR8dOUm6jXq7dEwoc7R/CFlDoVzeHid98SIzh7lVrGyyVQ33d9jq9m5HcJ3OeKZTSClx/O0sXlDmYl+BbK4W/qodN2J5MbgEMf9rlYqo2QXGbXu621fsy13dlVDr/NDjDubz0RCAQFIw9zVNhQzT5Ee6VL09egWoVWuyFw9tWMIwGGbia83m0l/CnhwJqdV9CprXihJzideKMvfutSyUFVc6Giee99yo8Uf28jlmTYxD4zUp1wWgciZHSQNsdt75buyOQKBPUB1oArRZ4gK7b67/zTJCiozUjXqUbTlTYYMJOas0WJ/Nmoo=',
    ),
    1 => 
    array (
      'encryption' => false,
      'signing' => true,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIIC5jCCAc6gAwIBAgIQHnpS2Z7PZ5tHST+oOHjGqTANBgkqhkiG9w0BAQsFADAvMS0wKwYDVQQDEyRBREZTIFNpZ25pbmcgLSBERVYtRlMtT05FLkdSUExFRy5DT00wHhcNMjMwNDI2MDAxMjA2WhcNMjgwNDI1MDAxMjA2WjAvMS0wKwYDVQQDEyRBREZTIFNpZ25pbmcgLSBERVYtRlMtT05FLkdSUExFRy5DT00wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6efxxRXrfYtWDAq5bp/8AJF7dOAoH56cZbjaLBo0mTQj6XUew91jzeRf7vuiH3ddWy+ucgo+RJQtGKUEknkEz/lgMhpOEC5glY7O9y9kTWxAOtrmbqpwltVwGkpvnch0t/zKdWCYlWeL1vb/Nnqy+CvPIlmK+wMlQ01K4gnP5iIfPsfPlaZwNNTqbWifq100MBnBuuU8EpbFCStNv2oHDlvuON/cgFwYJ3PFR7qljkp6ketbJuU2edLMkF37UOZJaLvfmPfFVpSKHwqgY0wZAMOK2UGpCaQ64wz2/cnOBlEmcuZgh0wU0M9X6PXTxrmTq30esDQ2QVyXGjDxI8Mp1AgMBAAEwDQYJKoZIhvcNAQELBQADggEBABeHhGPMZ9JptDB8XPnQcehMS7IFn4eVBL9qzLILLu+NAvp1zjMLQNfqMQx4LyjWaifmqYUk9zVs22TNKYjimiH5ctU58YAp2+njMpJNff1aujcrfr5Bfa6R/uyTGK79o5T680IKyvvr+4/MVw5DHdkz2Wrau2AqcO5QI/qq2X8f4KNr64EwK7LLZ+Tr2uN47Bu8Ax8Cf165gsEeIFAJ2peCYgcCdPwlxKHC7bVbtdTQzjkgSUuHnWJLCND/jx4kbySJz6kG6NDR6Y9au2HPnQSbY9s42dBMx/xNojd7shh+w2FasE0GS5TVMn5VesXeQak/63mh6X6CQSkT3larM1k=',
    ),
  ),
  'metarefresh:src' => 'https://dev-fs-one.grpleg.com/FederationMetadata/2007-06/FederationMetadata.xml',
  'expire' => 1693900863,
);
