<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8r8xhgn\SimpleSAML_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8r8xhgn/SimpleSAML_KernelProdContainer.php') {
    touch(__DIR__.'/Container8r8xhgn.legacy');

    return;
}

if (!\class_exists(SimpleSAML_KernelProdContainer::class, false)) {
    \class_alias(\Container8r8xhgn\SimpleSAML_KernelProdContainer::class, SimpleSAML_KernelProdContainer::class, false);
}

return new \Container8r8xhgn\SimpleSAML_KernelProdContainer([
    'container.build_hash' => '8r8xhgn',
    'container.build_id' => 'f24049f3',
    'container.build_time' => 1683793234,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8r8xhgn');
