<?php

namespace ContainerFO6rcEO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronService extends SimpleSAML_KernelProdContainer
{
    /*
     * Gets the public 'SimpleSAML\Module\cron\Controller\Cron' shared autowired service.
     *
     * @return \SimpleSAML\Module\cron\Controller\Cron
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['SimpleSAML\\Module\\cron\\Controller\\Cron'] = new \SimpleSAML\Module\cron\Controller\Cron(\SimpleSAML\Configuration::getInstance(), \SimpleSAML\Session::getSessionFromRequest());
    }
}
