<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}

require dirname(__DIR__, 4).'/vendor/autoload.php';
(require __DIR__.'/SimpleSAML_KernelProdContainer.php')->set(\ContainerWCrFxTT\SimpleSAML_KernelProdContainer::class, null);
require __DIR__.'/ContainerWCrFxTT/getServicesResetterService.php';
require __DIR__.'/ContainerWCrFxTT/getSecrets_VaultService.php';
require __DIR__.'/ContainerWCrFxTT/getHttpKernelService.php';
require __DIR__.'/ContainerWCrFxTT/getErrorControllerService.php';
require __DIR__.'/ContainerWCrFxTT/getContainer_EnvVarProcessorsLocatorService.php';
require __DIR__.'/ContainerWCrFxTT/getContainer_EnvVarProcessorService.php';
require __DIR__.'/ContainerWCrFxTT/getCache_SystemClearerService.php';
require __DIR__.'/ContainerWCrFxTT/getCache_SystemService.php';
require __DIR__.'/ContainerWCrFxTT/getCache_GlobalClearerService.php';
require __DIR__.'/ContainerWCrFxTT/getCache_AppClearerService.php';
require __DIR__.'/ContainerWCrFxTT/getCache_AppService.php';
require __DIR__.'/ContainerWCrFxTT/getArgumentResolver_ServiceService.php';
require __DIR__.'/ContainerWCrFxTT/getTemplateControllerService.php';
require __DIR__.'/ContainerWCrFxTT/getRedirectControllerService.php';
require __DIR__.'/ContainerWCrFxTT/getSessionService.php';
require __DIR__.'/ContainerWCrFxTT/getRedirectionService.php';
require __DIR__.'/ContainerWCrFxTT/getLogoutService.php';
require __DIR__.'/ContainerWCrFxTT/getLoginService.php';
require __DIR__.'/ContainerWCrFxTT/getExceptionService.php';
require __DIR__.'/ContainerWCrFxTT/getErrorReportService.php';
require __DIR__.'/ContainerWCrFxTT/getConfigurationService.php';
require __DIR__.'/ContainerWCrFxTT/get_ServiceLocator_KfbR3DYService.php';
require __DIR__.'/ContainerWCrFxTT/get_Container_Private_FilesystemService.php';
require __DIR__.'/ContainerWCrFxTT/get_Container_Private_CacheClearerService.php';

$classes = [];
$classes[] = 'Symfony\Bundle\FrameworkBundle\FrameworkBundle';
$classes[] = 'Symfony\Component\HttpKernel\CacheClearer\ChainCacheClearer';
$classes[] = 'Symfony\Component\Filesystem\Filesystem';
$classes[] = 'Symfony\Component\DependencyInjection\ServiceLocator';
$classes[] = 'SimpleSAML\Configuration';
$classes[] = 'SimpleSAML\Module\core\Controller\ErrorReport';
$classes[] = 'SimpleSAML\Module\core\Controller\Exception';
$classes[] = 'SimpleSAML\Module\core\Controller\Login';
$classes[] = 'SimpleSAML\Module\core\Controller\Logout';
$classes[] = 'SimpleSAML\Module\core\Controller\Redirection';
$classes[] = 'SimpleSAML\Session';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver';
$classes[] = 'Symfony\Component\Cache\Adapter\FilesystemAdapter';
$classes[] = 'Symfony\Component\Cache\Marshaller\DefaultMarshaller';
$classes[] = 'Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer';
$classes[] = 'Symfony\Component\Cache\Adapter\AdapterInterface';
$classes[] = 'Symfony\Component\Cache\Adapter\AbstractAdapter';
$classes[] = 'Symfony\Component\DependencyInjection\EnvVarProcessor';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\DebugHandlersListener';
$classes[] = 'Symfony\Component\HttpKernel\Debug\FileLinkFormatter';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ErrorController';
$classes[] = 'Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer';
$classes[] = 'Symfony\Component\EventDispatcher\EventDispatcher';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\ErrorListener';
$classes[] = 'Symfony\Component\HttpKernel\HttpKernel';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\ResponseListener';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ContainerControllerResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver';
$classes[] = 'Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactory';
$classes[] = 'SimpleSAML\Kernel';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\LocaleAwareListener';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\LocaleListener';
$classes[] = 'Symfony\Component\HttpKernel\Log\Logger';
$classes[] = 'Symfony\Component\HttpFoundation\RequestStack';
$classes[] = 'Symfony\Component\Routing\Router';
$classes[] = 'Symfony\Component\Routing\RequestContext';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\RouterListener';
$classes[] = 'Symfony\Component\Config\Loader\DelegatingLoader';
$classes[] = 'Symfony\Component\Config\Loader\LoaderResolver';
$classes[] = 'Symfony\Component\Routing\Loader\XmlFileLoader';
$classes[] = 'Symfony\Component\Config\FileLocator';
$classes[] = 'Symfony\Component\Routing\Loader\YamlFileLoader';
$classes[] = 'Symfony\Component\Routing\Loader\PhpFileLoader';
$classes[] = 'Symfony\Component\Routing\Loader\GlobFileLoader';
$classes[] = 'Symfony\Component\Routing\Loader\DirectoryLoader';
$classes[] = 'Symfony\Component\Routing\Loader\ContainerLoader';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Routing\AnnotatedRouteControllerLoader';
$classes[] = 'Symfony\Component\Routing\Loader\AnnotationDirectoryLoader';
$classes[] = 'Symfony\Component\Routing\Loader\AnnotationFileLoader';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Secrets\SodiumVault';
$classes[] = 'Symfony\Component\String\LazyString';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';
$classes[] = 'Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter';
$classes[] = 'Symfony\Component\String\Slugger\AsciiSlugger';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\StreamedResponseListener';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\ValidateRequestListener';

$preloaded = Preloader::preload($classes);
