<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWCrFxTT\SimpleSAML_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWCrFxTT/SimpleSAML_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWCrFxTT.legacy');

    return;
}

if (!\class_exists(SimpleSAML_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWCrFxTT\SimpleSAML_KernelProdContainer::class, SimpleSAML_KernelProdContainer::class, false);
}

return new \ContainerWCrFxTT\SimpleSAML_KernelProdContainer([
    'container.build_hash' => 'WCrFxTT',
    'container.build_id' => '04818424',
    'container.build_time' => 1683793236,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWCrFxTT');
