<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFO6rcEO\SimpleSAML_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFO6rcEO/SimpleSAML_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFO6rcEO.legacy');

    return;
}

if (!\class_exists(SimpleSAML_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFO6rcEO\SimpleSAML_KernelProdContainer::class, SimpleSAML_KernelProdContainer::class, false);
}

return new \ContainerFO6rcEO\SimpleSAML_KernelProdContainer([
    'container.build_hash' => 'FO6rcEO',
    'container.build_id' => 'da757f17',
    'container.build_time' => 1683891346,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFO6rcEO');
