<?php

namespace ContainerXuz4Yx0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetaRefreshService extends SimpleSAML_KernelProdContainer
{
    /*
     * Gets the public 'SimpleSAML\Module\metarefresh\Controller\MetaRefresh' shared autowired service.
     *
     * @return \SimpleSAML\Module\metarefresh\Controller\MetaRefresh
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['SimpleSAML\\Module\\metarefresh\\Controller\\MetaRefresh'] = new \SimpleSAML\Module\metarefresh\Controller\MetaRefresh(\SimpleSAML\Configuration::getInstance());
    }
}
