<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuz4Yx0\SimpleSAML_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuz4Yx0/SimpleSAML_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXuz4Yx0.legacy');

    return;
}

if (!\class_exists(SimpleSAML_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXuz4Yx0\SimpleSAML_KernelProdContainer::class, SimpleSAML_KernelProdContainer::class, false);
}

return new \ContainerXuz4Yx0\SimpleSAML_KernelProdContainer([
    'container.build_hash' => 'Xuz4Yx0',
    'container.build_id' => '7504da29',
    'container.build_time' => 1683891334,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuz4Yx0');
